# Generated by Django 4.1.2 on 2023-01-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=55, verbose_name='Category Slug')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Category Image')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, verbose_name='Contact Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject Message')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
            options={
                'verbose_name_plural': 'News Letters',
            },
        ),
        migrations.CreateModel(
            name='WhatsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='News Title')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='News', verbose_name='News Image')),
                ('description', models.TextField(verbose_name='News Description')),
                ('content', models.TextField(verbose_name='News Content')),
                ('category', models.CharField(choices=[('General', 'General'), ('Pag-asa', 'Pag-asa'), ('Department of Agriculture', 'Department of Agriculture')], default='General', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Crop Title')),
                ('slug', models.SlugField(max_length=160, verbose_name='Crop Slug')),
                ('crop_description', models.TextField(verbose_name='Crop Description')),
                ('crop_preparation', models.TextField(verbose_name='Crop Preparation')),
                ('crop_planting', models.TextField(verbose_name='Crop Planting')),
                ('crop_management', models.TextField(verbose_name='Pest and Disease Management')),
                ('risk_dry_pest', models.TextField(verbose_name='Risk Assessment Pest')),
                ('risk_dry_disease', models.TextField(verbose_name='Risk Assessment Disease')),
                ('prevention_dry_pest', models.TextField(verbose_name='Control & Prevention Pest')),
                ('prevention_dry_disease', models.TextField(verbose_name='Control & Prevention Disease')),
                ('risk_rainy_pest', models.TextField(verbose_name='Risk Assessment Pest')),
                ('risk_rainy_disease', models.TextField(verbose_name='Risk Assessment Disease')),
                ('prevention_rainy_pest', models.TextField(verbose_name='Control & Prevention Pest')),
                ('prevention_rainy_disease', models.TextField(verbose_name='Control & Prevention Disease')),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='Crop', verbose_name='Crop Image')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farms.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Crops',
            },
        ),
    ]
