# Generated by Django 4.1.2 on 2023-01-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsnew',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
