# Generated by Django 4.1.2 on 2023-01-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_whatsnew_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsnew',
            name='date',
        ),
    ]
